-- MySQL Script generated by MySQL Workbench
-- Sat Nov 14 01:17:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestor_permisos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gestor_permisos` ;

-- -----------------------------------------------------
-- Schema gestor_permisos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestor_permisos` DEFAULT CHARACTER SET utf8 COLLATE utf8_estonian_ci ;
USE `gestor_permisos` ;

-- -----------------------------------------------------
-- Table `gestor_permisos`.`Centros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_permisos`.`Centros` ;

CREATE TABLE IF NOT EXISTS `gestor_permisos`.`Centros` (
  `idCentro` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `acronimo` VARCHAR(100) NULL,
  PRIMARY KEY (`idCentro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_permisos`.`Estudios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_permisos`.`Estudios` ;

CREATE TABLE IF NOT EXISTS `gestor_permisos`.`Estudios` (
  `idEstudio` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `acronimo` VARCHAR(300) NULL,
  `Centros_idCentros` INT NOT NULL,
  `activo` TINYINT NULL,
  `tipo` ENUM('Grau', 'Màster') NULL,
  PRIMARY KEY (`idEstudio`, `Centros_idCentros`),
  INDEX `fk_Grados_Facultades1_idx` (`Centros_idCentros` ASC) VISIBLE,
  CONSTRAINT `fk_Grados_Facultades1`
    FOREIGN KEY (`Centros_idCentros`)
    REFERENCES `gestor_permisos`.`Centros` (`idCentro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_permisos`.`Departamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_permisos`.`Departamentos` ;

CREATE TABLE IF NOT EXISTS `gestor_permisos`.`Departamentos` (
  `idDepartamentos` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `acronimo` VARCHAR(100) NULL,
  PRIMARY KEY (`idDepartamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_permisos`.`Asignaturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_permisos`.`Asignaturas` ;

CREATE TABLE IF NOT EXISTS `gestor_permisos`.`Asignaturas` (
  `idAsignaturas` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idAsignaturas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_permisos`.`Profesores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_permisos`.`Profesores` ;

CREATE TABLE IF NOT EXISTS `gestor_permisos`.`Profesores` (
  `niu` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido1` VARCHAR(100) NOT NULL,
  `apellido2` VARCHAR(100) NULL,
  PRIMARY KEY (`niu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_permisos`.`Objeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_permisos`.`Objeto` ;

CREATE TABLE IF NOT EXISTS `gestor_permisos`.`Objeto` (
  `idObjeto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idObjeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_permisos`.`Anio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_permisos`.`Anio` ;

CREATE TABLE IF NOT EXISTS `gestor_permisos`.`Anio` (
  `inicio` INT NOT NULL,
  PRIMARY KEY (`inicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_permisos`.`Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_permisos`.`Grupo` ;

CREATE TABLE IF NOT EXISTS `gestor_permisos`.`Grupo` (
  `idGrupo` INT NOT NULL,
  `Anio_inicio` INT NOT NULL,
  PRIMARY KEY (`idGrupo`, `Anio_inicio`),
  INDEX `fk_Grupo_Anio1_idx` (`Anio_inicio` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_Anio1`
    FOREIGN KEY (`Anio_inicio`)
    REFERENCES `gestor_permisos`.`Anio` (`inicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_permisos`.`Asignaturas_has_Estudios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_permisos`.`Asignaturas_has_Estudios` ;

CREATE TABLE IF NOT EXISTS `gestor_permisos`.`Asignaturas_has_Estudios` (
  `Asignaturas_idAsignaturas` INT NOT NULL,
  `Estudios_idEstudios` INT NOT NULL,
  `Estudio_Centros_idCentros` INT NOT NULL,
  PRIMARY KEY (`Asignaturas_idAsignaturas`, `Estudios_idEstudios`, `Estudio_Centros_idCentros`),
  INDEX `fk_Asignaturas_has_Grados_Grados1_idx` (`Estudios_idEstudios` ASC, `Estudio_Centros_idCentros` ASC) VISIBLE,
  INDEX `fk_Asignaturas_has_Grados_Asignaturas1_idx` (`Asignaturas_idAsignaturas` ASC) VISIBLE,
  CONSTRAINT `fk_Asignaturas_has_Grados_Asignaturas1`
    FOREIGN KEY (`Asignaturas_idAsignaturas`)
    REFERENCES `gestor_permisos`.`Asignaturas` (`idAsignaturas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignaturas_has_Grados_Grados1`
    FOREIGN KEY (`Estudios_idEstudios` , `Estudio_Centros_idCentros`)
    REFERENCES `gestor_permisos`.`Estudios` (`idEstudio` , `Centros_idCentros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_permisos`.`Grupo_has_Asignaturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_permisos`.`Grupo_has_Asignaturas` ;

CREATE TABLE IF NOT EXISTS `gestor_permisos`.`Grupo_has_Asignaturas` (
  `Grupo_idGrupo` INT NOT NULL,
  `Asignaturas_idAsignaturas` INT NOT NULL,
  PRIMARY KEY (`Grupo_idGrupo`, `Asignaturas_idAsignaturas`),
  INDEX `fk_Grupo_has_Asignaturas_Asignaturas1_idx` (`Asignaturas_idAsignaturas` ASC) VISIBLE,
  INDEX `fk_Grupo_has_Asignaturas_Grupo1_idx` (`Grupo_idGrupo` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_has_Asignaturas_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `gestor_permisos`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_has_Asignaturas_Asignaturas1`
    FOREIGN KEY (`Asignaturas_idAsignaturas`)
    REFERENCES `gestor_permisos`.`Asignaturas` (`idAsignaturas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_permisos`.`Ambitos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_permisos`.`Ambitos` ;

CREATE TABLE IF NOT EXISTS `gestor_permisos`.`Ambitos` (
  `idAmbitos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `tabla` VARCHAR(100) NULL,
  PRIMARY KEY (`idAmbitos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_permisos`.`Cargos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_permisos`.`Cargos` ;

CREATE TABLE IF NOT EXISTS `gestor_permisos`.`Cargos` (
  `idCargos` INT NOT NULL,
  `descripcion` VARCHAR(300) NULL,
  `idEnAmbito` INT NULL,
  `Ambitos_idAmbitos` INT NOT NULL,
  PRIMARY KEY (`idCargos`, `Ambitos_idAmbitos`),
  INDEX `fk_Cargos_Ambitos1_idx` (`Ambitos_idAmbitos` ASC) VISIBLE,
  CONSTRAINT `fk_Cargos_Ambitos1`
    FOREIGN KEY (`Ambitos_idAmbitos`)
    REFERENCES `gestor_permisos`.`Ambitos` (`idAmbitos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_permisos`.`Permisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_permisos`.`Permisos` ;

CREATE TABLE IF NOT EXISTS `gestor_permisos`.`Permisos` (
  `idPermisos` INT NOT NULL,
  `nivel` ENUM('ninguno', 'basico', 'total') NULL DEFAULT 'ninguno',
  `Objeto_idObjeto` INT NOT NULL,
  `Ambitos_idAmbitos` INT NOT NULL,
  PRIMARY KEY (`idPermisos`, `Objeto_idObjeto`, `Ambitos_idAmbitos`),
  INDEX `fk_Permisos_Objeto1_idx` (`Objeto_idObjeto` ASC) VISIBLE,
  INDEX `fk_Permisos_Ambitos1_idx` (`Ambitos_idAmbitos` ASC) VISIBLE,
  CONSTRAINT `fk_Permisos_Objeto1`
    FOREIGN KEY (`Objeto_idObjeto`)
    REFERENCES `gestor_permisos`.`Objeto` (`idObjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Permisos_Ambitos1`
    FOREIGN KEY (`Ambitos_idAmbitos`)
    REFERENCES `gestor_permisos`.`Ambitos` (`idAmbitos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_permisos`.`Profesores_has_Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_permisos`.`Profesores_has_Grupo` ;

CREATE TABLE IF NOT EXISTS `gestor_permisos`.`Profesores_has_Grupo` (
  `Profesores_niu` INT NOT NULL,
  `Grupo_idGrupo` INT NOT NULL,
  `Grupo_Anio_inicio` INT NOT NULL,
  `ocupacion` INT NULL DEFAULT 0,
  PRIMARY KEY (`Profesores_niu`, `Grupo_idGrupo`, `Grupo_Anio_inicio`),
  INDEX `fk_Profesores_has_Grupo_Profesores1_idx` (`Profesores_niu` ASC) VISIBLE,
  INDEX `fk_Profesores_has_Grupo_Grupo1_idx` (`Grupo_idGrupo` ASC, `Grupo_Anio_inicio` ASC) VISIBLE,
  CONSTRAINT `fk_Profesores_has_Grupo_Profesores1`
    FOREIGN KEY (`Profesores_niu`)
    REFERENCES `gestor_permisos`.`Profesores` (`niu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesores_has_Grupo_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo` , `Grupo_Anio_inicio`)
    REFERENCES `gestor_permisos`.`Grupo` (`idGrupo` , `Anio_inicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_permisos`.`Departamentos_has_Profesores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_permisos`.`Departamentos_has_Profesores` ;

CREATE TABLE IF NOT EXISTS `gestor_permisos`.`Departamentos_has_Profesores` (
  `Departamentos_idDepartamentos` INT NOT NULL,
  `Profesores_niu` INT NOT NULL,
  PRIMARY KEY (`Departamentos_idDepartamentos`, `Profesores_niu`),
  INDEX `fk_Departamentos_has_Profesores_Profesores1_idx` (`Profesores_niu` ASC) VISIBLE,
  INDEX `fk_Departamentos_has_Profesores_Departamentos1_idx` (`Departamentos_idDepartamentos` ASC) VISIBLE,
  CONSTRAINT `fk_Departamentos_has_Profesores_Departamentos1`
    FOREIGN KEY (`Departamentos_idDepartamentos`)
    REFERENCES `gestor_permisos`.`Departamentos` (`idDepartamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Departamentos_has_Profesores_Profesores1`
    FOREIGN KEY (`Profesores_niu`)
    REFERENCES `gestor_permisos`.`Profesores` (`niu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_permisos`.`Cargos_has_Profesores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_permisos`.`Cargos_has_Profesores` ;

CREATE TABLE IF NOT EXISTS `gestor_permisos`.`Cargos_has_Profesores` (
  `Cargos_idCargos` INT NOT NULL,
  `Profesores_niu` INT NOT NULL,
  PRIMARY KEY (`Cargos_idCargos`, `Profesores_niu`),
  INDEX `fk_Cargos_has_Profesores_Profesores1_idx` (`Profesores_niu` ASC) VISIBLE,
  INDEX `fk_Cargos_has_Profesores_Cargos1_idx` (`Cargos_idCargos` ASC) VISIBLE,
  CONSTRAINT `fk_Cargos_has_Profesores_Cargos1`
    FOREIGN KEY (`Cargos_idCargos`)
    REFERENCES `gestor_permisos`.`Cargos` (`idCargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargos_has_Profesores_Profesores1`
    FOREIGN KEY (`Profesores_niu`)
    REFERENCES `gestor_permisos`.`Profesores` (`niu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
